## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    obj = bld.create_ns3_program('rftm', 
                                ['core', 'network', 'mobility', 'wifi', 'applications', 'internet'])
    obj.source = ['simulator.cc',
                 'vehicle.cc',
                 'rsu.cc',
                 'logging.cc']
